### ISSUE TITLE
误杀 无法加载

### ISSUE THREAD

**Issue by Dusk0531** [217heidai/adblockfilters#11]
![Screenshot_2023-10-29-16-43-32-69_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/217heidai/adblockfilters/assets/130734435/4b5b989c-d012-4d6b-bf91-c05501b3bab9)
d
![Screenshot_2023-10-29-16-43-34-14_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/217heidai/adblockfilters/assets/130734435/3626c26d-cda4-49c8-bdcc-5f8d103c6849)
![Screenshot_2023-10-29-16-44-13-34_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/217heidai/adblockfilters/assets/130734435/4b396eab-5e5f-4702-b67c-72d3c596ea11)
放行后恢复正常

**Comment by xingkongxiademodeng** [comment]
为什么加速链接连接不上呀？

**Comment by Dusk0531** [comment]
貌似崩了 我已经也用不了 开科学也用不了












千灯.
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月3日(周五) 中午11:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [217heidai/adblockfilters] 误杀 无法加载 (Issue #11)




 
为什么加速链接连接不上呀？

**Comment by 217heidai** [comment]
> 为什么加速链接连接不上呀？

这两天ghproxy.com代理访问不了

**Comment by 217heidai** [comment]
换github代理了，可以再试试
