### ISSUE TITLE
1Host 连招商银行都屏蔽。。。 还有其它的屏蔽了饿了么（支付宝客户端内置的）

### ISSUE THREAD

**Issue by wkii** [217heidai/adblockfilters#13]
屏蔽招行的是1host
屏蔽饿了么的不知道是哪个没完全确定。

**Comment by 217heidai** [comment]
1host 有屏蔽招行`||log.cmbchina.com^`，看域名应该是日志用的。
如果有影响，可以自行加一条放行规则：
@@||cmbchina.com^$important
