### ISSUE TITLE
加速镜像被封了

### ISSUE THREAD

**Issue by xxssww0258** [217heidai/adblockfilters#15]
主域名 ghproxy.com 已喜提 GFW，已启用镜像站 [mirror.ghproxy.com](https://mirror.ghproxy.com/)

**Comment by 217heidai** [comment]
> 主域名 ghproxy.com 已喜提 GFW，已启用镜像站 [mirror.ghproxy.com](https://mirror.ghproxy.com/)

更换为[mirror.ghproxy.com](https://mirror.ghproxy.com/)了。。。
