### ISSUE TITLE
请问api-shoulei-ssl.xunlei.com是否为误封

### ISSUE THREAD

**Issue by sorenniu** [217heidai/adblockfilters#16]
请求的APP为一个开源的视频软件-资源猫，在查看影视榜单的时候发现无法加载，检查拦截日志是给这个域名阻止了，没找到类似的议题，所以反馈确认下

**Comment by 217heidai** [comment]
查了下`api-shoulei-ssl.xunlei.com` 被 AdRules DNS List、NEO DEV HOST 拦截了，`get.sogou.com` 被 1Hosts (Lite) 拦截了，建议先临时添加放行(放行规则如`@@||example.org^$important`)，再向上游反馈。

**Comment by sorenniu** [comment]
好的，谢谢
