### ISSUE TITLE
误杀规则：AdRules AdBlock List

### ISSUE THREAD

**Issue by Mrbluewu** [217heidai/adblockfilters#2]
### **误杀规则：AdRules AdBlock List**

百度——导航栏——视频页，误杀视频列表
屏蔽规格如下：
`www.baidu.com#@##content_left > *:not([id]) *,[class="result c-container new-pmd"][id="1"][tpl="se_com_default"][data-click="{"]`

**Comment by 217heidai** [comment]
本项目只搬运、合并，不做任何修改。可以搜下引用的规则源，给原项目提建议。
