### ISSUE TITLE
可以考虑出两个版本，一个整合Anti-AD,一个不整合嘛，毕竟Anti-AD里面也有很多独有的很有用的规则

### ISSUE THREAD

**Issue by Lynricsy** [217heidai/adblockfilters#24]
可以考虑出两个版本，一个整合Anti-AD,一个不整合嘛，毕竟Anti-AD里面也有很多独有的很有用的规则

**Comment by Sereinfy** [comment]
其实残留的还有，就是不全。参考 [NEO DEV HOST](https://github.com/neodevpro/neodevhost?tab=readme-ov-file#sources-of-ad-hosts-data-%E5%8E%BB%E5%B9%BF%E5%91%8Ahost%E6%BA%90) 或者你可以fork 到自己的仓库。在README.md 里添加上去就行。过于简单，没必要出两个版本。

**Comment by doubleJazzCat** [comment]
![QQ截图20241210142120](https://github.com/user-attachments/assets/6033bae1-e276-471a-ab2a-44465b5da8db)
anti-AD反轮子, 好像没什么问题吧?
