### ISSUE TITLE
Discord 登录验证网址被拦截

### ISSUE THREAD

**Issue by MicIsHere** [217heidai/adblockfilters#34]
网址为:
click.discord.com

![IMG_3842](https://github.com/217heidai/adblockfilters/assets/76840547/a681e536-92f9-4a0f-8269-2be566e5ea90)
![IMG_3843](https://github.com/217heidai/adblockfilters/assets/76840547/89defe40-5e7c-4e4f-b248-cedce2e7a7d4)

**Comment by 217heidai** [comment]
已放行，更新规则重试下

**Comment by MicIsHere** [comment]
已解决
