### ISSUE TITLE
osfsr.lenovomm.com

### ISSUE THREAD

**Issue by higybibafi** [217heidai/adblockfilters#40]
osfsr.lenovomm.com 应该也是需要拦截的

**Comment by heichaowo** [comment]
我看不需要只有海外能ping到而且这个网址里没有实质的危害内容和服务
`root@cr0524020527:~# curl https://osfsr.lenovomm.com/
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Error Page</h3></body></html>`
