### ISSUE TITLE
微软服务被拦截

### ISSUE THREAD

**Issue by MeowRay** [217heidai/adblockfilters#43]
微软账号登录页面无法打开
https://login.live.com/

以及一些例如skype涉及微软账号的服务无法使用
这个问题于7月25日规则自动更新后出现

![image](https://github.com/user-attachments/assets/861d4ac8-f646-4d6d-9423-10b973a98063)

**Comment by 217heidai** [comment]
试了下，现在是可以访问的，应该上游规则已经修复了
