### ISSUE TITLE
ad为开头的全部网址被拦截

### ISSUE THREAD

**Issue by wq-zzz** [217heidai/adblockfilters#44]
[]()https://www.coolapk.com/feed/57743263
动态里的
例如[]()https://ad.yuwell.dynv6.net

**Comment by 217heidai** [comment]
已放行，更新规则试下

**Comment by wq-zzz** [comment]
> 已放行，更新规则试下

单纯加那一个网址白名单，治标不治本。主要是图片里那个拦截规则误杀的，
比如[]()https://ad.yuwell.dynv6.net/adblock_lite.txt
依然会被拦截
![Screenshot_20240726_143130.jpg](https://github.com/user-attachments/assets/8f31b4f5-cdf4-4830-93da-e52d3f78f920)

**Comment by 217heidai** [comment]
我用 AdGuardHome，可以正常打开<https://ad.yuwell.dynv6.net/adblock_lite.txt>。
<img width="1254" alt="iShot_2024-07-26_17 57 41" src="https://github.com/user-attachments/assets/b200a7df-6703-4f88-b311-6d56fd43d99d">
之前被拦截是上游[xinggsf rule](https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt)里有一条`||ad.`。看你这拦截提示，[xinggsf rule](https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt)里还有一条`*/ad.`，也得干掉。
