### ISSUE TITLE
哔哩哔哩数据接口被拦截

### ISSUE THREAD

**Issue by AdeSpike** [217heidai/adblockfilters#45]
哔哩哔哩的data.bilibili.com关键数据接口被拦截，导致全站无法访问。由于不清楚具体是哪个上游规则，只能来这里开个issue了，作者能更新下吗？
![22](https://github.com/user-attachments/assets/913168ae-7047-4063-9d07-1ddce804e1d0)
![11](https://github.com/user-attachments/assets/6fd96eb3-8e2e-4755-a3ee-de8f1c92b351)

**Comment by 217heidai** [comment]
刚试了下，cm.bilibili.com、data.bilibili.com 被拦截的情况下，浏览器能正常打开，视频也能观看。
