### ISSUE TITLE
rsc-api.ele.me 需要放行才能正常访问饿了么订单页面

### ISSUE THREAD

**Issue by heichaowo** [217heidai/adblockfilters#48]

**Comment by 217heidai** [comment]
拦截列表中未找到`rsc-api.ele.me`，再试试看，也有可能上游规则已修复

**Comment by heichaowo** [comment]
![image](https://github.com/user-attachments/assets/0069a98e-0b96-499c-80a2-83108870b0e3)
![image](https://github.com/user-attachments/assets/91ade452-d32d-4f0c-bf18-a1170e9df1cb)
![image](https://github.com/user-attachments/assets/18249882-b672-4a21-896a-fce72a8adb8a)
这个网址是tanx.com拦截的。之前我没有仔细的测试，这个地址跟订单页面没有关系，似乎是一个时间段会建立连接，猜测是向服务器上传什么东西，具体是干什么有待观察。

**Comment by 217heidai** [comment]
`tanx.com`整个二级域名被上游规则 [xinggsf rule](https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt)拦截了。已去掉`tanx.com`二级域名拦截，更新规则再试下。

**Comment by heichaowo** [comment]
![image](https://github.com/user-attachments/assets/eb488be1-6c57-4dbf-8c39-83698ea0292a)
问题已解决

**Comment by heichaowo** [comment]
"Tanx.com 是阿里巴巴集团旗下的一个广告和营销平台，名为 "Taobao Ad Network and Exchange"（TANX）。该平台为出版商、商家、需求方平台和第三方数据公司提供服务，主要功能包括实时广告交易和程序化购买，使广告分配更加高效和精准。通过使用阿里巴巴的广泛网络资源和数据管理技术，TANX 旨在提升广告和营销的效率，实现数字媒体的一站式全域传播。

阿里妈妈（Alimama）作为阿里巴巴的商业数字营销部门，依托TANX等平台，提供从广告投放到数据分析等一系列营销服务，帮助品牌和商家提升消费者运营的效果。​ (Tanx)​ ([Netify](https://www.netify.ai/resources/applications/tanx))
"
以上是ChatGPT的介绍，我认为这个rsc-api.ele.me大概率是与广告相关的api，因为我第一次提出iusse没有经过严谨的测试。总结，tanx.com应该被拦截。我对自己没有严谨的测试表示歉意。

**Comment by heichaowo** [comment]
直接访问tanx.com是这样的。
![image](https://github.com/user-attachments/assets/4edbbe30-96ec-45f7-adde-64acad21d5d6)
综上，tanx.com包括其子域名都是为广告服务的，应该保持拦截。
