### ISSUE TITLE
添加规则报错了, 应该是返回的内容太多了, 该怎么解决呢?

### ISSUE THREAD

**Issue by zzia531** [217heidai/adblockfilters#5]
![image](https://github.com/217heidai/adblockfilters/assets/99014153/72ccf1f1-539c-42a9-a73b-86a1d80d0e8c)

**Comment by kid1180** [comment]
同问

**Comment by MoonWWY** [comment]
AdGuardHome官网提醒：将单个规则的长度限制为 1024 字节来限制更新检查消耗的 RAM
需要规则作者解决：sed '/^.\{1024,\}/d' ./blocklist > ./blocklist_dns

**Comment by Deepsea-x** [comment]
+1 请问怎么解决

**Comment by dkgks** [comment]
@217heidai 麻烦解决一下，谢谢·
