### ISSUE TITLE
ynuf.aliapp.org 饿了么学生福利域名需要放行才能领取学生红包

### ISSUE THREAD

**Issue by jiajiaxd** [217heidai/adblockfilters#50]
ynuf.aliapp.org必须放行才能领取饿了么学生红包
![df218ae91f737854513faff18c249fc1](https://github.com/user-attachments/assets/86aad6cc-eff7-402f-a7ad-4aee33828e21)
![Screenshot_2024-08-20-09-40-49-912_me ele](https://github.com/user-attachments/assets/d4c91006-97eb-4fb8-b5c1-668a181141a9)

**Comment by 217heidai** [comment]
已放行，更新规则试下

**Comment by 217heidai** [comment]
已放行，更新规则试下
