### ISSUE TITLE
t.emailnotify.microsoft.com 需要放行才能访问微软奖励状态页

### ISSUE THREAD

**Issue by jiajiaxd** [217heidai/adblockfilters#51]
![image](https://github.com/user-attachments/assets/27648059-c386-4492-805c-2e0f59ffd921)
这条链接
![image](https://github.com/user-attachments/assets/5ee0123a-bc5e-472b-9951-a3aebc2c2631)

**Comment by 217heidai** [comment]
已放行，请更新规则试下

**Comment by jiajiaxd** [comment]
![image](https://github.com/user-attachments/assets/d94723ed-e95b-43af-b007-f3de2aa5e65c)
貌似添加错了？不应该添加t.emailnotify.microsoft.com吗

**Comment by 217heidai** [comment]
`t.emailnotify.microsoft.com` 解析会跳转到 `mscom-mkt-prod79-lb.campaign.adobe.com`，实际是被 `||campaign.adobe.com^`规则拦截的。
<img width="884" alt="image" src="https://github.com/user-attachments/assets/ac9bed66-f662-4086-afca-1f6c3e611701">

**Comment by jiajiaxd** [comment]
OK
