### ISSUE TITLE
腾讯视频无法播放

### ISSUE THREAD

**Issue by syunlee66** [217heidai/adblockfilters#59]
![image](https://github.com/user-attachments/assets/e5ac5371-60d0-4f17-a6e0-8cdbd1f35f80)

放行后可正常播放

**Comment by 217heidai** [comment]
已放行，更新规则再试下

**Comment by yyds1980** [comment]
这个是什么东西？这个怎么用的？谢谢！

**Comment by syunlee66** [comment]
> 这个是什么东西？这个怎么用的？谢谢！

openwrt 的 AdGuardHome 的查询日志
