### ISSUE TITLE
Adguard浏览器插件，添加无效

### ISSUE THREAD

**Issue by LordHumphrey** [217heidai/adblockfilters#6]
AdGuard 浏览器扩展
版本 4.1.57
添加了啥反应没有，添加的加速链接，原始链接，均无效

**Comment by jibukeshi** [comment]
经测试 AdGuard 的扩展功能需要使用 root 全校将它的 CA 证书移动到系统证书才有效，在没有 root 的设备上扩展是不生效的。

**Comment by hang1233** [comment]
换AdBlock

**Comment by 217heidai** [comment]
更新下版本试试，我用的4.2.189版，可以正常添加。

**Comment by 217heidai** [comment]
去掉连不通的域名，压缩了40%，可以再试试
