### ISSUE TITLE
哔哩哔哩网页视频评论区无法显示

### ISSUE THREAD

**Issue by TullyMonster** [217heidai/adblockfilters#7]
![20230901154041](https://github.com/217heidai/adblockfilters/assets/47771282/70203ee3-9ac7-4b2e-9356-4bb5a811a7f6)

**Comment by 217heidai** [comment]
可以向源规则库项目反馈下，本项目只是对常用规则库的搬运、合并，未做任何修改，源规则库更新这边就同步更新了。
