### ISSUE TITLE
提示您已达到用户添加规则的限制

### ISSUE THREAD

**Issue by van23qf** [217heidai/adblockfilters#70]
过滤器中显示您已达到用户添加规则的限制。 5000 条规则中的 10772 条已启用。

请问这个应该怎么解决

**Comment by fangyuan99** [comment]
确实，我也显示这个，希望出个lite版本

**Comment by fangyuan99** [comment]
> 这个限制已经导致最新版adg没法用了，用了个离线老版本

佬推荐个版本号呗

**Comment by 217heidai** [comment]
试下lite版，只保留了国内广告域名拦截

**Comment by mightyants** [comment]
相同问题，规则1DNS一个就 18万条规则。直接超出了15万规则限制。给我整不会了

**Comment by mightyants** [comment]
内容拦截器，最多限制15W的规则。规则1DNS一个就 18万条规则。直接超出了15万规则限制。给我整不会了。求求解决方案

**Comment by 217heidai** [comment]
> 内容拦截器，最多限制15W的规则。规则1DNS一个就 18万条规则。直接超出了15万规则限制。给我整不会了。求求解决方案

试下lite版
