### ISSUE TITLE
皮皮虾搜索短视频无法搜索

### ISSUE THREAD

**Issue by mhggv** [217heidai/adblockfilters#8]
这个域名dig.bdurl.net皮皮虾搜索用的返回搜索内容，我看你规则里写的是||dig.bdurl.net^

**Comment by 217heidai** [comment]
查了下这个域名在几个规则库里都命中了AdGuard DNS filter、AdRules DNS List、1Hosts、Hblock、NEO DEV HOST、oisd small，需要等上游更新。
你可以先临时加一条放行规则：@@||dig.bdurl.net^$important
