### ISSUE TITLE
腾讯视频网页端播放失败

### ISSUE THREAD

**Issue by Duan-rax** [217heidai/adblockfilters#80]
使用此规则后，腾讯视频网页端无法播放，一直转圈，怀疑是无法正常播放广告，已登录VIP情况下依旧无法正常播放

**Comment by Duan-rax** [comment]
网站是可以正常浏览的，图片也可以加载，单纯无法播放视频

**Comment by 217heidai** [comment]
试了下PC端浏览器打开播放是正常的，看下拦截记录呢。
![image](https://github.com/user-attachments/assets/da391746-f5c4-4321-94dc-94909da49a88)

**Comment by Duan-rax** [comment]
24-10-21 18:25:12[ debug ][3231713306 5.65s] dns: exchanged pgdt.gtimg.cn NOERROR 0
24-10-21 18:25:12[ debug ][3231713306 5.64s] dns: match[0] rule_set=[geosite-category-ads-all adblock-dns-filters] => dns_block
24-10-21 18:25:12[ debug ][3231713306 5.64s] dns: exchange pgdt.gtimg.cn. IN A
24-10-21 18:25:12[ info ][1899641700 1ms] outbound/direct[direct]: outbound connection to 183.194.189.94:443
24-10-21 18:25:12[ debug ][1899641700 1ms] router: match[26] rule_set=[geosite-private geoip-private geosite-cn geoip-cn] => 🌏 cn
24-10-21 18:25:12[ debug ][1899641700 0ms] router: sniffed protocol: tls, domain: wuji.video.qq.com
24-10-21 18:25:12[ info ][1899641700 0ms] inbound/tun[0]: inbound connection to 183.194.189.94:443
24-10-21 18:25:12[ info ][1899641700 0ms] inbound/tun[0]: inbound connection from 172.19.0.1:50944
24-10-21 18:25:12[ debug ][135506169 10.86s] dns: exchanged snowflake.qq.com NOERROR 0
24-10-21 18:25:12[ debug ][135506169 10.86s] dns: match[0] rule_set=[geosite-category-ads-all adblock-dns-filters] => dns_block
24-10-21 18:25:12[ debug ][135506169 10.86s] dns: exchange snowflake.qq.com. IN A
24-10-21 18:25:12[ debug ][3231713306 5.15s] dns: exchanged beacon.cdn.qq.com NOERROR 0
24-10-21 18:25:12[ debug ][3231713306 5.15s] dns: match[0] rule_set=[geosite-category-ads-all adblock-dns-filters] => dns_block
24-10-21 18:25:12[ debug ][3231713306 5.15s] dns: exchange beacon.cdn.qq.com. IN A
24-10-21 18:25:11[ debug ][135506169 10.17s] dns: exchanged iwan-s.video.qq.com NOERROR 0
24-10-21 18:25:11[ debug ][135506169 10.17s] dns: match[0] rule_set=[geosite-category-ads-all adblock-dns-filters] => dns_block
24-10-21 18:25:11[ debug ][135506169 10.17s] dns: exchange iwan-s.video.qq.com. IN A
24-10-21 18:25:11[ debug ][3231713306 4.47s] dns: exchanged vd6.l.qq.com NOERROR 0
24-10-21 18:25:11[ debug ][3231713306 4.47s] dns: match[0] rule_set=[geosite-category-ads-all adblock-dns-filters] => dns_block
24-10-21 18:25:11[ debug ][3231713306 4.47s] dns: exchange vd6.l.qq.com. IN A
24-10-21 18:25:10[ debug ][135506169 9.42s] dns: exchanged vi.l.qq.com NOERROR 0
24-10-21 18:25:10[ debug ][135506169 9.42s] dns: match[0] rule_set=[geosite-category-ads-all adblock-dns-filters] => dns_block
24-10-21 18:25:10[ debug ][135506169 9.42s] dns: exchange vi.l.qq.com. IN A
24-10-21 18:25:10[ debug ][3522034520 21.69s] inbound/tun[0]: connection closed: context canceled
24-10-21 18:25:10[ debug ][3231713306 3.40s] dns: exchanged otheve.beacon.qq.com NOERROR 0
24-10-21 18:25:10[ debug ][3231713306 3.40s] dns: match[0] rule_set=[geosite-category-ads-all adblock-dns-filters] => dns_block
24-10-21 18:25:10[ debug ][3231713306 3.40s] dns: exchange otheve.beacon.qq.com. IN A
24-10-21 18:25:10[ debug ][131325877 21.46s] inbound/tun[0]: connection closed: context canceled
24-10-21 18:25:10[ debug ][68316572 12.2s] inbound/tun[0]: connection closed: context canceled
24-10-21 18:25:10[ debug ][3133729351 21.19s] inbound/tun[0]: connection closed: context canceled
24-10-21 18:25:10[ debug ][4036348959 21.15s] inbound/tun[0]: connection closed: context canceled

**Comment by Duan-rax** [comment]
我使用的是此问题下的这个项目，转给sing-box使用的，似乎看不到具体日志，应该是兼容性问题。
