### ISSUE TITLE
staticsns.cdn.bcebos.com 属于百度静态文件域名 应当放行

### ISSUE THREAD

**Issue by jiajiaxd** [217heidai/adblockfilters#82]
![image](https://github.com/user-attachments/assets/c78608e1-2339-4d6d-956a-f390b25b1141)
![image](https://github.com/user-attachments/assets/52d11845-49f0-4a9a-9a6e-0c699423f3de)
![image](https://github.com/user-attachments/assets/1a2ce2fd-857b-4c95-81b2-75e1e69af4ee)

**Comment by 217heidai** [comment]
已放行，更新规则试下
