### ISSUE TITLE
规则1 ads.youtube.com导致直播中断无法播放

### ISSUE THREAD

**Issue by raydoomed** [217heidai/adblockfilters#84]
里面有给规则ads.youtube.com好像影响到了youtube直播观看，youtube会检测到广告过滤会中断直播无法播放

**Comment by 217heidai** [comment]
有不能播放的视频链接吗，点了首页上几个都能正常播放

**Comment by raydoomed** [comment]
> 有不能播放的视频链接吗，点了首页上几个都能正常播放
播放直播，大概1分钟内就会出错！视频是没问题的，就直播有问题

**Comment by raydoomed** [comment]
> 有不能播放的视频链接吗，点了首页上几个都能正常播放

https://www.youtube.com/watch?v=xXZMSTuJKAg
https://www.youtube.com/watch?v=EfFOcL3nyFE

**Comment by 217heidai** [comment]
两个看了十几分钟，没有遇到`ads.youtube.com`域名。。。
![image](https://github.com/user-attachments/assets/d1680765-04e4-46cd-9304-6910aa727a25)

**Comment by raydoomed** [comment]
![mmexport1731409235480.jpg](https://github.com/user-attachments/assets/d8308378-db10-46f4-b017-ae7c25f7bd6d)

![Screenshot_20241112_185221_Chrome.jpg](https://github.com/user-attachments/assets/cb7d2006-6ac9-4a8f-8d86-5dca82e5547d)

只要勾选这个规则，就会出错

**Comment by raydoomed** [comment]
![mmexport1731412956997.png](https://github.com/user-attachments/assets/e5b1063d-8d7b-4e21-abaa-fdd49d23c25f)

找到问题了，添加此规则后解决！

**Comment by 217heidai** [comment]
放行`jnn-pa.googleapis.com`了，更新规则再试下

**Comment by raydoomed** [comment]
> 放行`jnn-pa.googleapis.com`了，更新规则再试下

ok谢谢
