### ISSUE TITLE
www.cnnic.com.cn 不应该拦截

### ISSUE THREAD

**Issue by jiajiaxd** [217heidai/adblockfilters#85]
![image](https://github.com/user-attachments/assets/79a7ae49-e1fc-43b5-8484-bd727c62a47f)
这也不是广告啊...拦截了感觉有点夹带私货了？

**Comment by 217heidai** [comment]
`www.cnnic.com.cn`会跳转到`www.cnnic.cn`，上游[NEO DEV HOST](https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker)不干净，拦截了：
![image](https://github.com/user-attachments/assets/9775a41d-adcc-4fe9-a664-94b76a402fbd)

**Comment by 217heidai** [comment]
> > `www.cnnic.com.cn`会跳转到`www.cnnic.cn`，上游[NEO DEV HOST](https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker)不干净，拦截了： ![image](https://github.com/user-attachments/assets/9775a41d-adcc-4fe9-a664-94b76a402fbd)
> 
> 曾在 [https://github.com/neodevpro/neodevhost/issues/31中遇到过这个问题，想问下现在还能否信任https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker](https://github.com/neodevpro/neodevhost/issues/31%E4%B8%AD%E9%81%87%E5%88%B0%E8%BF%87%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%8C%E6%83%B3%E9%97%AE%E4%B8%8B%E7%8E%B0%E5%9C%A8%E8%BF%98%E8%83%BD%E5%90%A6%E4%BF%A1%E4%BB%BBhttps://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker) ？

NEO DEV HOST 上游引用了[anti-AD](https://github.com/privacy-protection-tools/anti-AD)，关于 anti-AD 的争议可以看下<https://github.com/Mosney/anti-anti-AD>，可以自行评估下是否使用
