### ISSUE TITLE
华为应用商店登录被拦截

### ISSUE THREAD

**Issue by little3tar** [217heidai/adblockfilters#87]
DNS 规则中:"||oauth-login-drcn.platform.dbankcloud.com^"拦截了华为应用商店的登录请求，无法正常登录华为账号。

AdGuard 建议的规则:"@@||oauth-login-drcn.platform.dbankcloud.com^$app=com.huawei.hwid"

**Comment by 217heidai** [comment]
已放行，请更新规则再试下
