### ISSUE TITLE
加速链接显示502 Bad Gateway

### ISSUE THREAD

**Issue by lzkids** [217heidai/adblockfilters#89]
是我网络的问题还是什么？
![Screenshot_2024-12-08-19-54-35-39_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/735476bb-34c2-4cab-8dc6-17030ad1467b)
显示这个

**Comment by 217heidai** [comment]
应该是代理站的问题，刚试了下已经恢复了
