### ISSUE TITLE
Adguardhome添加不上

### ISSUE THREAD

**Issue by d01ag0n** [217heidai/adblockfilters#9]
能不能拆成两部分，太大了

**Comment by 217heidai** [comment]
> 能不能拆成两部分，太大了

去掉连不通的域名，压缩了40%，可以再试试

**Comment by lzqd** [comment]
> > 能不能拆成两部分，太大了
> 
> 去掉连不通的域名，压缩了40%，可以再试试

AdGuard DNS filter这个规则存在错误拦截建议去除
