### ISSUE TITLE
可否增加 dnsmasq 格式规则

### ISSUE THREAD

**Issue by Aethersailor** [217heidai/adblockfilters#97]
大佬可否增加 dnsmasq 格式规则？目前找到的去广告规则中您的规则最全面也不臃肿，很希望能在dnsmasq下使用
该格式可用于 openwrt 系统下 dnsmasq 直接加载从而实现去广告
具体格式如该文件所示
https://raw.githubusercontent.com/neodevpro/neodevhost/refs/heads/master/dnsmasq.conf
感谢大佬

**Comment by 217heidai** [comment]
已更新，请试下规则4
