### ISSUE TITLE
Have you tried hagezi ultimate list ?

### ISSUE THREAD

**Issue by Greatz08** [217heidai/adblockfilters#99]
Pretty great adblock list overall so i thought to share it with you since i found nothing related to hagezi in issues and description . Been using it for a long time :-)
https://github.com/hagezi/dns-blocklists

**Comment by 217heidai** [comment]
Thanks for the suggestions. [DNS-Blocklists Light](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt) has been added.
